<!-- MAIN CONTENT -->
<div id="content" class="container">

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
            <?=$this->partial('content.text');?>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
            <div class="well no-padding">
                <form method="post" id="wsgi-form-recover" class="smart-form client-form">
                    <header>
                        Forgot Password
                    </header>

                    <fieldset>

                        <section>
                            <label class="label">Enter your email address</label>
                            <label class="input"> <i class="icon-append fa fa-envelope"></i>
                                <input type="email" name="email">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-envelope txt-color-teal"></i> Please enter email address for password reset</b></label>
                        </section>
                        <section>
										<span class="timeline-seperator text-center text-primary"> <span class="font-sm">OR</span>
                        </section>
                        <section>
                            <label class="label">Your Username</label>
                            <label class="input"> <i class="icon-append fa fa-user"></i>
                                <input type="text" name="username">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Enter your username</b> </label>
                            <div class="note">
                                <a href="<?=backend_url('/auth/signin')?>">Lembrei da minha senha</a>
                            </div>
                        </section>

                    </fieldset>
                    <footer>
                        <button type="submit" class="btn btn-primary">
                            <i class="fa fa-refresh"></i> Reset Password
                        </button>
                    </footer>
                </form>

            </div>

            <h5 class="text-center"> - Or sign in using -</h5>

            <ul class="list-inline text-center">
                <li>
                    <a href="javascript:void(0);" class="btn btn-primary btn-circle"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                    <a href="javascript:void(0);" class="btn btn-info btn-circle"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                    <a href="javascript:void(0);" class="btn btn-warning btn-circle"><i class="fa fa-linkedin"></i></a>
                </li>
            </ul>

        </div>
    </div>
</div>

{% put script %}
<script type="text/javascript">


</script>
{% endput %}