<!-- MAIN CONTENT -->
<div id="content" class="container">

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
            <?=$this->partial('content.text');?>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
            <div class="well no-padding">
                <form method="post" id="wsgi-form-login" class="smart-form client-form">
                    <header>
                        Login
                    </header>

                    <fieldset>

                        <section>
                            <label class="label">E-mail</label>
                            <label class="input"> <i class="icon-append fa fa-user"></i>
                                <input type="text" name="Auth[username]">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i>Informe seu email ou username</b></label>
                        </section>

                        <section>
                            <label class="label">Senha</label>
                            <label class="input"> <i class="icon-append fa fa-lock"></i>
                                <input type="password" name="Auth[password]">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i>Informe sua senha</b> </label>
                            <div class="note">
                                <a href="<?=backend_url('/auth/recover')?>">Esqueceu sua senha ?</a>
                            </div>
                        </section>

                        <section>
                            <label class="checkbox">
                                <input type="checkbox" name="Auth[remember]" checked="">
                                <i></i>Continuar conectado</label>
                        </section>
                    </fieldset>
                    <footer>
                        <button type="submit" class="btn btn-primary">
                            Logar
                        </button>
                    </footer>
                </form>

            </div>

            <!--
            <h5 class="text-center"> - Or sign in using -</h5>

            <ul class="list-inline text-center">
                <li>
                    <a href="javascript:void(0);" class="btn btn-primary btn-circle"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                    <a href="javascript:void(0);" class="btn btn-info btn-circle"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                    <a href="javascript:void(0);" class="btn btn-warning btn-circle"><i class="fa fa-linkedin"></i></a>
                </li>
            </ul>

            -->
        </div>
    </div>
</div>

{% put script %}
<script type="text/javascript">
    runAllForms();

    $(function() {
        // Validation
        $("#wsgi-form-login").validate({
            // Rules for form validation
            rules : {
                email : {
                    required : true,
                    email : true
                },
                password : {
                    required : true,
                    minlength : 3,
                    maxlength : 20
                }
            },

            // Messages for form validation
            messages : {
                email : {
                    required : 'Please enter your email address',
                    email : 'Please enter a VALID email address'
                },
                password : {
                    required : 'Please enter your password'
                }
            },

            // Do not change code below
            errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
            }
        });
    });
</script>
{% endput %}