<div id="controleModal">

    <div id="modalList" class="wsgi-modal-content" title="<div class='widget-header'><h4><i class='fa fa-list'></i> Listagem</h4></div>" style="display: none;">
    </div>

    <div id="modalForm" class="wsgi-modal-content" title="<div class='widget-header'><h4><i class='fa fa-plus'></i> Salvar</h4></div>" style="display: none;">
    </div>

</div><!-- //#controleModal -->