<h1 class="txt-color-blue login-header-big">wSGI - Sistema de Gerenciamento Imobiliário</h1>
<div class="hero">

    <div class="pull-left login-desc-box-l">
        <h4 class="paragraph-header">Tenho o total controle de sua imobiliária a qualquer hora e em qualquer lugar.</h4>
        <div class="login-app-icons">
            <a href="javascript:void(0);" class="btn btn-default btn-sm">Frontend Template</a>
            <a href="javascript:void(0);" class="btn btn-default btn-sm">Find out more</a>
        </div>
    </div>

    <img src="<?=tpl_assets('img/demo/iphoneview.png')?>" class="pull-right display-image" alt="" style="width:210px">

</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <h5 class="about-heading">About SmartAdmin - Are you up to date?</h5>
        <p>
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.
        </p>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <h5 class="about-heading">Not just your average template!</h5>
        <p>
            Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi voluptatem accusantium!
        </p>
    </div>
</div>