<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBKtVmqOE0OI2o6FUxmCtmVLZDyFqBKlFE">
</script>

<!-- row -->
<div class="row">

    <!-- NEW WIDGET START -->
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <!-- Widget ID (each widget will need unique ID)-->
        <div
            class="jarviswidget"
            id="wid-id-0"
            data-widget-colorbutton="false"
            data-widget-editbutton="false"
            data-widget-deletebutton="false"
            data-widget-custombutton="false"
        >
            <!-- widget options:
                usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                data-widget-colorbutton="false"
                data-widget-editbutton="false"
                data-widget-togglebutton="false"
                data-widget-deletebutton="false"
                data-widget-fullscreenbutton="false"
                data-widget-custombutton="false"
                data-widget-collapsed="true"
                data-widget-sortable="false"

            -->
            <header>
                <span class="widget-icon"> <i class="fa fa-list"></i> </span>
                <h2>Dados do imóvel</h2>
            </header>

            <!-- widget div-->
            <div>

                <!-- widget edit box -->
                <div class="jarviswidget-editbox">
                    <!-- This area used as dropdown edit box -->
                    <input class="form-control" type="text">
                </div>
                <!-- end widget edit box -->

                <!-- widget content -->
                <div class="widget-body wsgi-data">
                    <div class="row" style="margin-bottom: 12px">

                        <?php
                        $sSituacao = '';
                        if ($this->val('Imovel.Situacao') == 'Alugado')   $sSituacao = '<span class="center-block padding-5 label label-primary">Alugado</span>';
                        if ($this->val('Imovel.Situacao') == 'Livre')     $sSituacao = '<span class="center-block padding-5 label label-success">Livre</span>';
                        if ($this->val('Imovel.Situacao') == 'Vendido')   $sSituacao = '<span class="center-block padding-5 label label-danger">Vendido</span>';
                        if ($this->val('Imovel.Situacao') == 'Reservado') $sSituacao = '<span class="center-block padding-5 label label-warning">Reservado</span>';
                        if ($this->val('Imovel.Situacao') == 'Negociação') $sSituacao = '<span class="center-block padding-5 label bg-color-purple txt-color-white">Negociação</span>';



                        ?>

                        <div class="col-xs-2" style="text-align: center">
                            <div style="font-weight: bold">Situação do imóvel:</div> <div id="LabelSituacao"><?=$sSituacao?></div>
                        </div>
                    </div>
                    <form id="movieForm" method="post" action="<?=$this->DataPoint();?>">
                        <input type="hidden" name="<?=$this->csrf->set('_token')?>" value="<?=$this->csrf->token('_token')?>">
                        <ul id="myTab1" class="nav nav-tabs bordered">
                            <li class="active"><a href="#s1" data-toggle="tab"><i class="fa fa-fw fa-lg fa-home"></i>Dados do imóvel</a></li>
                            <li><a href="#s2" data-toggle="tab"><i class="fa fa-fw fa-lg fa-language"></i>Dados Adicionais</a></li>
                            <li><a href="#s3" data-toggle="tab"><i class="fa fa-fw fa-lg fa-dollar"></i> Valores</a></li>
                            <li><a href="#s4" data-toggle="tab"><i class="fa fa-fw fa-lg fa-phone"></i> Ligações telefônicas</a></li>
                            <li><a href="#s5" data-toggle="tab"><i class="fa fa-fw fa-lg fa-map-marker"></i> Mapa</a></li>
                            <li><a href="#s6" data-toggle="tab"><i class="fa fa-fw fa-lg fa-suitcase"></i> Contratos de aluguel</a></li>
                            <li><a href="#s7" data-toggle="tab"><i class="fa fa-fw fa-lg fa-legal"></i> Propostas de venda</a></li>
                            <li><a href="#s8" data-toggle="tab"><i class="fa fa-fw fa-lg fa-paperclip"></i> Anexos</a></li>
                        </ul>
                        <div id="myTabContent1" class="tab-content padding-10">
                            <!--Tab Dados do imovel-->
                            <div class="tab-pane fade in active" id="s1" style="padding-left: 10px">
                                <!--Informações basicas do imovel-->
                                <div class="row">
                                    <!-- Linha 1 - IDs -->
                                    <fieldset>
                                        <legend>Informações básicas do imóvel</legend>
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <div class="row">
                                                    <div class="col-xs-2">
                                                        <div class="form-group<?php $e = $this->err('Imovel.DataCriacao') ?>">
                                                            <label for="EdDtCadastro">Data de Cadastro</label>
                                                            <input type="text" disabled id="EdDtCadastro" class="form-control" name="<?= $this->csrf->set('Imovel[DataCriacao]') ?>" value="<?=date('d/m/Y H:i', strtotime($this->val('Imovel.DataCriacao')))?>" readonly>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-2">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Pasta') ?>">
                                                            <label for="EdPasta">Pasta/Contrato</label>
                                                            <input type="text" id="EdPasta" class="form-control" placeholder="" maxlength="30" name="<?= $this->csrf->set('Imovel[Pasta]') ?>" value="<?=$this->val('Imovel.Pasta')?>" set-focus>
                                                            <span class="help-block"><?= $e ?></span>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-2">
                                                        <div class="form-group<?php $e = $this->err('Imovel.NumSite') ?>">
                                                            <label for="EdNumSite">Nº Site</label>
                                                            <input type="text" id="EdNumSite" class="form-control" name="<?= $this->csrf->set('Imovel[NumSite]') ?>" value="<?=$this->val('Imovel.NumSite')?>" maxlength="100">
                                                            <span class="help-block"><?= $e ?></span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-xs-2">
                                                        <div class="form-group<?php $e = $this->err('Imovel.TipoImovelId') ?>">
                                                            <label for="CbTipoImovel">Tipo do Imóvel</label>
                                                            <span><a style="float: right; font-size: 12px; font-weight: bold; cursor: pointer">Novo</a></span>
                                                            <?php $v = $this->val('Imovel.TipoImovelId'); ?>
                                                            <select class="form-control" name="<?= $this->csrf->set('Imovel[TipoImovelId]') ?>">
                                                                <option value="">-- Tipo do imóvel --</option>
                                                                <?php foreach ($this->model->TiposImovel() as $obj): $_v = $obj->Id; ?>
                                                                    <option value="<?=$_v?>"<?=($v==$_v ? ' selected' : '')?>><?=$obj->Nome?></option>
                                                                <?php endforeach; ?>
                                                            </select>
                                                            <span class="help-block"><?= $e ?></span>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-2">
                                                        <div class="form-group<?php $e = $this->err('Imovel.FinalidadeImovelId') ?>">
                                                            <label for="CbFinalidade">Finalidade do Imóvel</label>
                                                            <span><a style="float: right; font-size: 12px; font-weight: bold; cursor: pointer">Novo</a></span>
                                                            <?php $v = $this->val('Imovel.FinalidadeImovelId'); ?>
                                                            <select class="form-control" name="<?= $this->csrf->set('Imovel[FinalidadeImovelId]') ?>">
                                                                <option value="">-- Tipo do imóvel --</option>
                                                                <?php foreach ($this->model->FinalidadesImovel() as $obj): $_v = $obj->Id; ?>
                                                                    <option value="<?=$_v?>"<?=($v==$_v ? ' selected' : '')?>><?=$obj->Nome?></option>
                                                                <?php endforeach; ?>
                                                            </select>
                                                            <span class="help-block"><?= $e ?></span>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-4">
                                                        <div class="form-group<?php $e = $this->err('Imovel.FinalidadeDescricao') ?>">
                                                            <label for="EdDescricaoFinalidade">Descrição da Finalidade</label>
                                                            <input type="text" id="EdDescricaoFinalidade" class="form-control" name="<?= $this->csrf->set('Imovel[FinalidadeDescricao]') ?>" value="<?=$this->val('Imovel.FinalidadeDescricao')?>">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </fieldset>

                                </div>

                                <!--Endereço-->
                                <div class="row">
                                    <fieldset>
                                        <legend>Endereço</legend>
                                        <!-- Informações basicas-->
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <!--2ª Linha informaçóes basicas -->
                                                <div class="row">
                                                    <div class="col-xs-2">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Endereco.CEP') ?>">
                                                            <label for="EdCEP">CEP</label>
                                                            <div class="input-group">
                                                                <input type="text" id="EdCEP" class="form-control" name="<?= $this->csrf->set('Imovel[Endereco[Cep]]') ?>" value="<?=$this->val('Imovel.Endereco.Cep')?>">
                                                                <span class="input-group-btn">
                                                                        <button type="button" id="BtBuscaCEP" class="btn btn-default" style="height: 32px;"><i class="fa fa-search"></i></button>
                                                                    </span>
                                                            </div><!-- /input-group -->
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-3">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Endereco.Logradouro') ?>">
                                                            <label for="EdLogradouro">Logradouro</label>
                                                            <input type="text" id="EdLogradouro" class="form-control" placeholder="" name="<?= $this->csrf->set('Imovel[Endereco[Logradouro]]') ?>" value="<?=$this->val('Imovel.Endereco.Logradouro')?>">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-3">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Endereco.Complemento') ?>">
                                                            <label for="EdComplemento">Complemento</label>
                                                            <input type="text" id="EdComplemento" class="form-control" placeholder="" name="<?= $this->csrf->set('Imovel[Endereco[Complemento]]') ?>" value="<?=$this->val('Imovel.Endereco.Complemento')?>">
                                                        </div>
                                                    </div>
                                                </div>
                                                <!--3ª Linha informaçóes basicas -->
                                                <div class="row">
                                                    <div class="col-xs-2">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Endereco.Bairro') ?>">
                                                            <label for="EdBairro">Bairro</label>
                                                            <input type="text" id="EdBairro" class="form-control" placeholder="" name="<?= $this->csrf->set('Imovel[Endereco[Bairro]]') ?>" value="<?=$this->val('Imovel.Endereco.Bairro')?>">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Endereco.Numero') ?>">
                                                            <label for="EdEnderecoNumero">Número</label>
                                                            <input type="text" id="EdEnderecoNumero" class="form-control" placeholder="" name="<?= $this->csrf->set('Imovel[Endereco[Numero]]') ?>" value="<?=$this->val('Imovel.Endereco.Numero')?>">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Endereco.Quadra') ?>">
                                                            <label for="EdEnderecoQuadra">Quadra</label>
                                                            <input type="text" id="EdEnderecoQuadra" class="form-control" placeholder="" name="<?= $this->csrf->set('Imovel[Endereco[Quadra]]') ?>" value="<?=$this->val('Imovel.Endereco.Quadra')?>">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Endereco.Lote') ?>">
                                                            <label for="EdEnderecoLote">Lote</label>
                                                            <input type="text" id="EdEnderecoLote" class="form-control" placeholder="" name="<?= $this->csrf->set('Imovel[Endereco[Lote]]') ?>" value="<?=$this->val('Imovel.Endereco.Lote')?>">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-3">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Endereco.Cidade.Id') ?>">
                                                            <label for="CbCidade">Cidades</label>
                                                            <span><a style="float: right; font-size: 12px; font-weight: bold; cursor: pointer">Novo</a></span>
                                                            <?php $v = $this->val('Imovel.Endereco.CidadeId'); ?>
                                                            <select class="form-control" id="CbEnderecoCidade" name="<?= $this->csrf->set('Imovel[Endereco[CidadeId]]') ?>">
                                                                <option value="">-- Cidade --</option>
                                                                <?php foreach ($this->model->Endereco->Cidades() as $obj): $_v = $obj->Id; ?>
                                                                    <option value="<?=$_v?>"<?=($v==$_v ? ' selected' : '')?>><?=$obj->Nome?></option>
                                                                <?php endforeach; ?>
                                                            </select>
                                                            <span class="help-block"><?= $e ?></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </fieldset>
                                </div>

                                <!--Pessoas relacionadas ao imovel-->
                                <div class="row">
                                    <fieldset>
                                        <legend>Pessoas relacionadas ao imóvel (Proprietários / Fiadores / Procuradores / etc )</legend>
                                        <!-- Pessoas relacionadas com o imovel-->
                                        <div class="row" style="padding-right: 10px;">
                                            <div class="col-xs-12">
                                                <div class="row">
                                                    <div class="col-xs-12" style="text-align: right; margin-bottom: 7px">
                                                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModalAddPessoas" id="btn_new_contract" onclick="ModalAdicionarPessoas()">
                                                            <i class="fa fa-user"></i>&nbsp;
                                                            Adicionar pessoas
                                                        </button>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-xs-12">
                                                        <table id="TbPessoasImovel" name="TbPessoasImovel" class="table data-table table-striped table-bordered table-hover" width="100%">
                                                            <thead>
                                                            <tr>
                                                                <th data-class="expand"><i class="fa fa-fw fa-user text-muted hidden-md hidden-sm hidden-xs "></i> Nome/Razão social</th>
                                                                <th data-hide="phone" class=""></i> CPF/CNPJ</th>
                                                                <th data-hide="phone" class="centralizado"><i class="fa fa-fw fa-code-fork text-muted hidden-md hidden-sm hidden-xs"></i> Tipo Vinculo</th>
                                                                <th class="centralizado">Percentual</th>
                                                                <th class="centralizado">Ações</th>
                                                            </thead>

                                                            <?php if($all = $this->model->PessoasVinculadas->all()): ?>
                                                                <tbody>
                                                                <?php foreach ($all as $i => $o): $i++; ?>
                                                                    <tr id="tr_<?=$o->Id?>" class="row-data <?=($o->TipoVinculo->Nome == 'Proprietario' ? 'txt-color-magenta ' : '')?>">
                                                                        <td class=""><?=$o->Pessoa->Nome?></td>
                                                                        <td class=""><?=$o->Pessoa->CpfCnpj?></td>
                                                                        <td class="centralizado <?=($o->TipoVinculo->Nome == 'Proprietario' ? 'negrito ' : '')?>"><?=$o->TipoVinculo->Nome?></td>
                                                                        <td class="centralizado"><?=$o->Percentual?> %</td>
                                                                        <td class="centralizado"><a idvinculo="<?=$o->Id?>" nomepessoa="<?=$o->Pessoa->Nome?>" class="btn btn-danger btn-xs" id="BtExcluirPessoa">Excluir</a></td>
                                                                    </tr>
                                                                <?php endforeach; ?>
                                                                </tbody>
                                                            <?php else: ?>
                                                                <tbody>
                                                                <tr>
                                                                    <td colspan="4" class="sem-registro"><i class="fa fa-info-circle"></i> Esse imóvel ainda não possuí pessoas vinculas a ele. </td>
                                                                </tr>
                                                                </tbody>
                                                            <?php endif; ?>

                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </fieldset>
                                </div>

                                <!-- Dados do empreendimento-->
                                <div class="row">
                                    <fieldset>
                                        <legend>Informações do Empreendimento</legend>
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <div class="row">
                                                    <div class="col-xs-4">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Id') ?>">
                                                            <label for="CbLoteamento">Empreendimento</label>
                                                            <span><a style="float: right; font-size: 12px; font-weight: bold; cursor: pointer" href="/sistema/empreendimentos/cadastro" target="_blank" rel="tooltip" data-placement="right" data-original-title="Ao clicar será aberta uma nova janela para se cadastrar o empreendimento">Novo</a></span>
                                                            <?php $v = $this->val('Imovel.EmpreendimentoId'); ?>
                                                            <select class="form-control" name="<?= $this->csrf->set('Imovel[EmpreendimentoId]') ?>">
                                                                <option value="">-- Empreendimento --</option>
                                                                <?php foreach ($this->model->Empreendimentos() as $obj): $_v = $obj->Id; ?>
                                                                    <option value="<?=$_v?>"<?=($v==$_v ? ' selected' : '')?>><?=$obj->Nome?></option>
                                                                <?php endforeach; ?>
                                                            </select>
                                                            <span class="help-block"><?= $e ?></span>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <label for="CbLoteamento">&nbsp;</label>
                                                        <?=$this->val('Imovel.EmpreendimentoId') ? '<a target="_blank" class="btn btn-primary" href='.backend_url('/empreendimentos/editar/'.$this->val('Imovel.EmpreendimentoId')).'><i class="fa fa-eye"></i> Visualizar Empreendimento</a>' : '' ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </fieldset>
                                </div>

                                <!-- Dados de reserva e exigencias-->
                                <div class="row">

                                    <!-- Reserva-->
                                    <div class="col-xs-5" style="padding-left: 0px" >
                                        <fieldset>
                                            <legend>Reserva</legend>
                                            <div class="col-xs-6 xs-sem-margem" style="padding-bottom: 10px">
                                                <label class="radio radio-inline no-margin" style="padding-left: 0px">
                                                    <?php $v = $this->val('Imovel.Reservado'); ?>
                                                    <input type="checkbox" name="<?= $this->csrf->set('Imovel[Reservado]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                    <span>Imóvel reservado no momento</span>
                                                </label>

                                            </div>
                                            <div class="col-xs-6">
                                                <div style="float: right">
                                                    <a type="submit" class="btn btn-primary btn-xs"><i class="fa fa-history"></i>   Histórico de reservas</a>
                                                </div>
                                            </div>
                                            <div class="col-xs-8 xs-sem-margem">
                                                <div class="form-group<?php $e = $this->err('Imovel.ReservadoData') ?>">
                                                    <label for="CbCorretor">Reservado para o corretor</label>
                                                    <select class="form-control" name="<?= $this->csrf->set('Imovel[CorretorId]') ?>">
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-xs-4">
                                                <div class="form-group<?php $e = $this->err('Imovel.ReservadoDataFim') ?>">
                                                    <div class="form-group<?php $e = $this->err('Imovel.ReservadoDataFim') ?>">
                                                        <label for="EdDataFimReserva">Data final da reserva</label>
                                                        <input type="date" id="EdDataFimReserva" class="form-control" name="<?= $this->csrf->set('Imovel.ReservadoDataFim') ?>" value="<?=($this->val('Imovel.ReservadoDataFim') == '' ? '' : date('Y-m-d', strtotime($this->val('Imovel.ReservadoDataFim'))))?>">
                                                    </div>
                                                </div>
                                            </div>
                                        </fieldset>
                                    </div>

                                    <!-- Exigencias-->
                                    <div class="col-xs-5" style="padding-left: 0">
                                        <fieldset>
                                            <legend>Exigências</legend>
                                            <div class="col-xs-6 xs-sem-margem">
                                                <label class="radio radio-inline no-margin" style="padding-left: 0px">
                                                    <?php $v = $this->val('Imovel.ExigFiador'); ?>
                                                    <input type="checkbox" value="1" class="checkbox style-1" name="<?= $this->csrf->set('Imovel[ExigFiador]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                    <span>Fiador</span>
                                                </label><br/>
                                                <label class="radio radio-inline no-margin" style="padding-left: 0px">
                                                    <?php $v = $this->val('Imovel.ExigDeposito'); ?>
                                                    <input type="checkbox" value="1" class="checkbox style-1" name="<?= $this->csrf->set('Imovel[ExigDeposito]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                    <span>Depósito</span>
                                                </label><br/>
                                                <label class="radio radio-inline no-margin" style="padding-left: 0px">
                                                    <?php $v = $this->val('Imovel.ExigSeguroFianca'); ?>
                                                    <input type="checkbox" value="1" class="checkbox style-1" name="<?= $this->csrf->set('Imovel[ExigSeguroFianca]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                    <span>Segura fiança</span>
                                                </label><br/>
                                                <label class="radio radio-inline no-margin" style="padding-left: 0px">
                                                    <?php $v = $this->val('Imovel.ExigExclusividade'); ?>
                                                    <input type="checkbox" value="1" class="checkbox style-1" name="<?= $this->csrf->set('Imovel[ExigExclusividade]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                    <span>Exclusividade</span>
                                                </label>
                                            </div>
                                            <div class="col-xs-6">
                                                <label class="radio radio-inline no-margin" style="padding-left: 0px">
                                                    <?php $v = $this->val('Imovel.ExigVisitaCorredor'); ?>
                                                    <input type="checkbox" value="1" class="checkbox style-1" name="<?= $this->csrf->set('Imovel[ExigVisitaCorredor]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                    <span>Visita com corretor</span>
                                                </label><br/>
                                                <label class="radio radio-inline no-margin" style="padding-left: 0px">
                                                    <?php $v = $this->val('Imovel.ExigAltoPadrao'); ?>
                                                    <input type="checkbox" value="1" class="checkbox style-1" name="<?= $this->csrf->set('Imovel[ExigAltoPadrao]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                    <span>Alto padrão</span>
                                                </label><br/>
                                                <label class="radio radio-inline no-margin" style="padding-left: 0px">
                                                    <?php $v = $this->val('Imovel.ExigTemporada'); ?>
                                                    <input type="checkbox" value="1" class="checkbox style-1" name="<?= $this->csrf->set('Imovel[ExigTemporada]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                    <span>Temporada</span>
                                                </label>
                                            </div>
                                        </fieldset>
                                    </div>

                                </div>

                                <!--Dados da procuração-->
                                <div class="row">
                                    <!-- Dados de cartorio-->
                                    <fieldset>
                                        <legend>Dados da procuração</legend>
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <div class="row">
                                                    <div class="col-xs-3">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Id') ?>">
                                                            <label for="CbProcurador">Procurador</label>
                                                            <input type="hidden" id="EdIdProcurador" [formControl]="formulario.controls['ProcuradorId']">
                                                            <input type="text" id="EdNomeProcurador" class="form-control" [formControl]="formulario.controls['ProcuradorNome']">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-4">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Cartorio') ?>">
                                                            <div class="form-group<?php $e = $this->err('Imovel.Cartorio') ?>">
                                                                <label for="EdCartProc">Cartório procuração</label>
                                                                <input type="text" id="EdCartProc" class="form-control" name="<?= $this->csrf->set('Imovel[Cartorio]') ?>" value="<?=$this->val('Imovel.Cartorio')?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.CartorioLivro') ?>">
                                                            <div class="form-group<?php $e = $this->err('Imovel.CartorioLivro') ?>">
                                                                <label for="EdLivroProc">Livro</label>
                                                                <input type="text" id="EdLivroProc" class="form-control" name="<?= $this->csrf->set('Imovel[CartorioLivro]') ?>" value="<?=$this->val('Imovel.CartorioLivro')?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.CartorioFolhas') ?>">
                                                            <div class="form-group<?php $e = $this->err('Imovel.CartorioFolhas') ?>">
                                                                <label for="EdFolhaProc">Folha</label>
                                                                <input type="text" id="EdFolhaProc" class="form-control" name="<?= $this->csrf->set('Imovel[CartorioFolhas]') ?>" value="<?=$this->val('Imovel.CartorioFolhas')?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-2">
                                                        <div class="form-group<?php $e = $this->err('Imovel.DataProcuracao') ?>">
                                                            <div class="form-group<?php $e = $this->err('Imovel.DataProcuracao') ?>">
                                                                <label for="EdDataProc">Data da Procuração</label>
                                                                <input type="date" id="EdDataProc" class="form-control" name="<?= $this->csrf->set('Imovel[DataProcuracao]') ?>" value="<?=($this->val('Imovel.DataProcuracao') == '' ? '' : date('Y-m-d', strtotime($this->val('Imovel.DataProcuracao'))))?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.CartorioMatriculaCartorio') ?>">
                                                            <div class="form-group<?php $e = $this->err('Imovel.CartorioMatriculaCartorio') ?>">
                                                                <label for="EdMatCart">Matrícula cartório</label>
                                                                <input type="text" id="EdMatCart" class="form-control" name="<?= $this->csrf->set('Imovel[CartorioMatriculaCartorio]') ?>" value="<?=$this->val('Imovel.CartorioMatriculaCartorio')?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.CartorioNumOrdem') ?>">
                                                            <div class="form-group<?php $e = $this->err('Imovel.CartorioNumOrdem') ?>">
                                                                <label for="EdOrdemCart">Nº Ordem</label>
                                                                <input type="text" id="EdOrdemCart" class="form-control" name="<?= $this->csrf->set('Imovel[CartorioNumOrdem]') ?>" value="<?=$this->val('Imovel.CartorioNumOrdem')?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.CartorioNumFicha') ?>">
                                                            <div class="form-group<?php $e = $this->err('Imovel.CartorioNumFicha') ?>">
                                                                <label for="EdNumFicha">Nº Ficha</label>
                                                                <input type="text" id="EdNumFicha" class="form-control" name="<?= $this->csrf->set('Imovel[CartorioNumFicha]') ?>" value="<?=$this->val('Imovel.CartorioNumFicha')?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.CartorioLivroRegistro') ?>">
                                                            <div class="form-group<?php $e = $this->err('Imovel.CartorioLivroRegistro') ?>">
                                                                <label for="EdLivroReg">Livro</label>
                                                                <input type="text" id="EdLivroReg" class="form-control" name="<?= $this->csrf->set('Imovel[CartorioLivroRegistro]') ?>" value="<?=$this->val('Imovel.CartorioLivroRegistro')?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.CartorioFolhaRegistro') ?>">
                                                            <div class="form-group<?php $e = $this->err('Imovel.CartorioFolhaRegistro') ?>">
                                                                <label for="EdFolhaReg">Folha</label>
                                                                <input type="text" id="EdFolhaReg" class="form-control" name="<?= $this->csrf->set('Imovel[CartorioFolhaRegistro]') ?>" value="<?=$this->val('Imovel.CartorioFolhaRegistro')?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-2">
                                                        <div class="form-group<?php $e = $this->err('Imovel.CartorioDataRegistro') ?>">
                                                            <div class="form-group<?php $e = $this->err('Imovel.CartorioDataRegistro') ?>">
                                                                <label for="EdDataReg">Data de Registro</label>
                                                                <input type="date" id="EdDataReg" class="form-control data" name="<?= $this->csrf->set('Imovel[CartorioDataRegistro]') ?>" value="<?=($this->val('Imovel.CartorioDataRegistro') == '' ? '' : date('Y-m-d', strtotime($this->val('Imovel.CartorioDataRegistro'))))?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </fieldset>
                                </div>
                            </div>

                            <!--Tab Dados adicional-->
                            <div class="tab-pane fade" id="s2">

                                <ul id="myTab2" class="nav nav-tabs bordered">
                                    <li class="active"><a href="#ss1" data-toggle="tab">Características</a></li>
                                    <li><a href="#ss2" data-toggle="tab">Características avançadas</a></li>
                                    <li><a href="#ss3" data-toggle="tab"></i> Divulgações</a></li>
                                    <!--                                        <li><a href="#ss4" data-toggle="tab"></i> Acessórios</a></li>-->
                                </ul>
                                <div id="myTabContent2" class="tab-content padding-10">
                                    <!--Caracteristica-->
                                    <div class="tab-pane fade in active" id="ss1">
                                        <!--Metragem-->
                                        <div class="row">
                                            <div class="col-xs-12 xs-sem-margem">
                                                <fieldset>
                                                    <legend>Metragem</legend>
                                                    <div class="col-xs-12" style="padding-left: 0px">
                                                        <div class="col-xs-1">
                                                            <div class="form-group<?php $e = $this->err('Imovel.AreaTerreno') ?>">
                                                                <label for="EdTerreno">Área do terreno</label>
                                                                <input type="number" id="EdTerreno" class="form-control" name="<?= $this->csrf->set('Imovel[AreaTerreno]') ?>" value="<?=$this->val('Imovel.AreaTerreno')?>">
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-1">
                                                            <div class="form-group<?php $e = $this->err('Imovel.AreaContruida') ?>">
                                                                <label for="EdAreaContruida">Área construída</label>
                                                                <input type="number" id="EdAreaContruida" class="form-control" name="<?= $this->csrf->set('Imovel[AreaContruida]') ?>" value="<?=$this->val('Imovel.AreaContruida')?>">
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-1">
                                                            <div class="form-group<?php $e = $this->err('Imovel.AreaMedidasFrente') ?>">
                                                                <label for="EdFrente">Frente</label>
                                                                <input type="number" id="EdFrente" class="form-control" name="<?= $this->csrf->set('Imovel[AreaMedidasFrente]') ?>" value="<?=$this->val('Imovel.AreaMedidasFrente')?>">
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-1">
                                                            <div class="form-group<?php $e = $this->err('Imovel.AreaMedidasFrente') ?>">
                                                                <label for="EdFundo">Fundo</label>
                                                                <input type="number" id="EdFundo" class="form-control" name="<?= $this->csrf->set('Imovel[AreaMedidasFrente]') ?>" value="<?=$this->val('Imovel.AreaMedidasFrente')?>">
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-1">
                                                            <div class="form-group<?php $e = $this->err('Imovel.AreaMedidasDireita') ?>">
                                                                <label for="EdLadoDireito">Lado direito</label>
                                                                <input type="number" id="EdLadoDireito" class="form-control" name="<?= $this->csrf->set('Imovel[AreaMedidasDireita]') ?>" value="<?=$this->val('Imovel.AreaMedidasDireita')?>">
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-1">
                                                            <div class="form-group<?php $e = $this->err('Imovel.AreaMedidasEsquerda') ?>">
                                                                <label for="EdLadoEsquerdo">Lado esquerdo</label>
                                                                <input type="number" id="EdLadoEsquerdo" class="form-control" name="<?= $this->csrf->set('Imovel[AreaMedidasEsquerda]') ?>" value="<?=$this->val('Imovel.AreaMedidasEsquerda')?>">
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-1">
                                                            <div class="form-group<?php $e = $this->err('Imovel.Chanfro') ?>">
                                                                <label for="EdChanfro">Chanfro</label>
                                                                <input type="text" id="EdChanfro" class="form-control" name="<?= $this->csrf->set('Imovel[Chanfro]') ?>" value="<?=$this->val('Imovel.Chanfro')?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </fieldset>
                                            </div>
                                        </div>

                                        <!--Caracteristicas basicas do imovel #1-->
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <fieldset>
                                                    <legend>Detalhes do imóvel</legend>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Quartos') ?>">
                                                            <label for="EdQuartos">Quartos</label>
                                                            <input type="text" id="EdQuartos" class="form-control" name="<?= $this->csrf->set('Imovel[Quartos]') ?>" value="<?=$this->val('Imovel.Quartos')?>">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Suites') ?>">
                                                            <label for="EdSuites">Suítes</label>
                                                            <input type="text" id="EdSuites" class="form-control" name="<?= $this->csrf->set('Imovel[Suites]') ?>" value="<?=$this->val('Imovel.Suites')?>">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Banheiros') ?>">
                                                            <label for="EdBanheiros">Banheiros</label>
                                                            <input type="text" id="EdBanheiros" class="form-control" name="<?= $this->csrf->set('Imovel[Banheiros]') ?>" value="<?=$this->val('Imovel.Banheiros')?>">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Salas') ?>">
                                                            <label for="EdSalas">Salas</label>
                                                            <input type="text" id="EdSalas" class="form-control" name="<?= $this->csrf->set('Imovel[Salas]') ?>" value="<?=$this->val('Imovel.Salas')?>">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <div class="form-group<?php $e = $this->err('Imovel.Garagem') ?>">
                                                            <label for="EdGaragem">Garagem</label>
                                                            <input type="text" id="EdGaragem" class="form-control" name="<?= $this->csrf->set('Imovel[Garagem]') ?>" value="<?=$this->val('Imovel.Garagem')?>">
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-1">
                                                        <label class="radio radio-inline no-margin">
                                                            <?php $v = $this->val('Imovel.Muro'); ?>
                                                            <input type="checkbox" name="<?= $this->csrf->set('Imovel[Muro]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                            <span>Muro</span>
                                                        </label>

                                                    </div>
                                                    <div class="col-xs-2">
                                                        <label class="radio radio-inline no-margin">
                                                            <?php $v = $this->val('Imovel.CercaEletrica'); ?>
                                                            <input type="checkbox" name="<?= $this->csrf->set('Imovel[CercaEletrica]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                            <span>Cerca elétrica</span>
                                                        </label>
                                                    </div>
                                                </fieldset>
                                            </div>
                                        </div>

                                        <!--Caracteristicas basicas do imovel #2-->
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <div class="col-xs-1 xs-sem-margem">
                                                    <div class="form-group<?php $e = $this->err('Imovel.GaragemBoxNumero') ?>">
                                                        <label for="EdNumBox">Nº Box/Vaga</label>
                                                        <input type="text" id="EdNumBox" class="form-control" name="<?= $this->csrf->set('Imovel[GaragemBoxNumero]') ?>" value="<?=$this->val('Imovel.GaragemBoxNumero')?>">
                                                    </div>
                                                </div>
                                                <div class="col-xs-2">
                                                    <div class="form-group<?php $e = $this->err('Imovel.GaragemBoxTipo') ?>">
                                                        <label for="EdTipoBox">Tipo Garagem/Box</label>
                                                        <input type="text" id="EdTipoBox" class="form-control" name="<?= $this->csrf->set('Imovel[GaragemBoxTipo]') ?>" value="<?=$this->val('Imovel.GaragemBoxTipo')?>">
                                                    </div>
                                                </div>
                                                <div class="col-xs-2">
                                                    <div class="form-group<?php $e = $this->err('Imovel.UnidadeAutonoma') ?>">
                                                        <label for="EdUndAuto">Unidade autónoma</label>
                                                        <input type="text" id="EdUndAuto" class="form-control" name="<?= $this->csrf->set('Imovel[UnidadeAutonoma]') ?>" value="<?=$this->val('Imovel.UnidadeAutonoma')?>">
                                                    </div>
                                                </div>
                                                <div class="col-xs-2">
                                                    <div class="form-group<?php $e = $this->err('Imovel.CaracEscaninho') ?>">
                                                        <label for="EdEscaninho">Escaninho</label>
                                                        <input type="text" id="EdEscaninho" class="form-control" name="<?= $this->csrf->set('Imovel[CaracEscaninho]') ?>" value="<?=$this->val('Imovel.CaracEscaninho')?>">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <!--Caracteristicas basicas do imovel #3-->
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <div class="col-xs-1 xs-sem-margem">
                                                    <div class="form-group<?php $e = $this->err('Imovel.Torre') ?>">
                                                        <label for="EdTorre">Torre</label>
                                                        <input type="text" id="EdTorre" class="form-control" name="<?= $this->csrf->set('Imovel[Torre]') ?>" value="<?=$this->val('Imovel.Torre')?>">
                                                    </div>
                                                </div>
                                                <div class="col-xs-1">
                                                    <div class="form-group<?php $e = $this->err('Imovel.Andar') ?>">
                                                        <label for="EdAndar">Andar</label>
                                                        <input type="text" id="EdAndar" class="form-control" name="<?= $this->csrf->set('Imovel[Andar]') ?>" value="<?=$this->val('Imovel.Andar')?>">
                                                    </div>
                                                </div>
                                                <div class="col-xs-1">
                                                    <div class="form-group<?php $e = $this->err('Imovel.NumApto') ?>">
                                                        <label for="EdNumApto">Nº Apartamento</label>
                                                        <input type="text" id="EdNumApto" class="form-control" name="<?= $this->csrf->set('Imovel[NumApto]') ?>" value="<?=$this->val('Imovel.NumApto')?>">
                                                    </div>
                                                </div>
                                                <div class="col-xs-3">
                                                    <div class="form-group<?php $e = $this->err('Imovel.TipoLajeId') ?>">
                                                        <label for="CbTipoLaje">Tipo de laje</label>
                                                        <?php $v = $this->val('Imovel.TipoLajeId'); ?>
                                                        <select class="form-control" name="<?= $this->csrf->set('Imovel[TipoLajeId]') ?>">
                                                            <option value="">-- Tipo de laje --</option>
                                                            <?php foreach ($this->model->TiposLaje() as $obj): $_v = $obj->Id; ?>
                                                                <option value="<?=$_v?>"<?=($v==$_v ? ' selected' : '')?>><?=$obj->Nome?></option>
                                                            <?php endforeach; ?>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <!--Descrição geral do imovel-->
                                        <div class="row">
                                            <div class="col-xs-12 xs-sem-margem">
                                                <fieldset>
                                                    <legend>Descrição geral do imóvel</legend>
                                                    <div class="col-xs-6 xs-sem-margem">
                                                        <textarea id="MmDescricao" class="form-control no-resize-textarea"><?=$this->val('Imovel.DescricaoGeralImovel')?></textarea>
                                                    </div>
                                                </fieldset>
                                            </div>
                                        </div>

                                        <!--Outros detalhes-->
                                        <div class="row">
                                            <div class="col-xs-12 xs-sem-margem">
                                                <fieldset>
                                                    <legend>Outros detalhes</legend>
                                                    <div class="col-xs-6 xs-sem-margem">
                                                        <textarea id="MmOutrosDetalhes" class="form-control no-resize-textarea"><?=$this->val('Imovel.OutrosDetalhes')?></textarea>
                                                    </div>
                                                </fieldset>
                                            </div>
                                        </div>

                                        <!--Observações-->
                                        <div class="row">
                                            <div class="col-xs-12 xs-sem-margem">
                                                <fieldset>
                                                    <legend>Observações</legend>
                                                    <div class="col-xs-6 xs-sem-margem">
                                                        <textarea id="MmObs" class="form-control no-resize-textarea"><?=$this->val('Imovel.Observacoes')?></textarea>
                                                    </div>
                                                </fieldset>
                                            </div>
                                        </div>
                                    </div>

                                    <!--Caracteristicas avançadas-->
                                    <div class="tab-pane fade" id="ss2">
                                        <div class="row">
                                            <div class="col-xs-12" style="text-align: right; margin-bottom: 7px">
                                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModalAddCaracteristicas" id="btn_new_contract" onclick="ModalAdicionarCaracteristica()">
                                                    <i class="fa fa-plus-square"></i>&nbsp;
                                                    Adicionar característica
                                                </button>
                                            </div>
                                        </div>
                                        <table class="table data-table table-striped table-bordered table-hover" width="100%" id="TbCaracteristicasAvancadas">
                                            <thead>
                                            <tr>
                                                <th>Nome caracteristica</th>
                                                <th>Descrição</th>
                                                <th>Data cadastro</th>
                                            </tr>
                                            </thead>
                                            <?php if($all = $this->model->CaracteristicasAvancadas->all()): ?>
                                                <tbody>
                                                <?php foreach ($all as $i => $o): $i++; ?>
                                                    <tr class="row-data">
                                                        <td class="cell-link"><?=$o->Caracteristica->Nome?></td>
                                                        <td class="cell-link"><?=$o->Descricao?></td>
                                                        <td class="cell-link"><?=date('d/m/Y H:i', strtotime($o->DataCriacao))?></td>
                                                    </tr>
                                                <?php endforeach; ?>
                                                </tbody>
                                            <?php else: ?>
                                                <tbody>
                                                <tr>
                                                    <td colspan="3" class="sem-registro"><i class="fa fa-info-circle"></i> Esse imóvel ainda não possuí caracteristicas cadastradas. </td>
                                                </tr>
                                                </tbody>
                                            <?php endif; ?>
                                            </tbody>
                                        </table>
                                    </div>

                                    <!--Divulgacoes-->
                                    <div class="tab-pane fade" id="ss3">
                                        <!-- Placa de divulgação-->
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <fieldset>
                                                    <legend>Placa de divulgação</legend>
                                                    <div class="row">
                                                        <div class="col-xs-2">
                                                            <div class="form-group<?php $e = $this->err('Imovel.DivulgacaoPlaca') ?>">
                                                                <label class="radio radio-inline no-margin">
                                                                    <?php $v = $this->val('Imovel.DivulgacaoPlaca'); ?>
                                                                    <input type="checkbox" name="<?= $this->csrf->set('Imovel[DivulgacaoPlaca]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                                    <span>Possúi placa de divulgação afixida?</span>
                                                                </label>
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-2">
                                                            <div class="form-group<?php $e = $this->err('Imovel.DivulgacaoPlacaData') ?>">
                                                                <label for="EdDataColocacaoPlaca">Data que foi colocada a placa</label>
                                                                <input type="date" id="EdDataColocacaoPlaca" class="form-control"  name="<?= $this->csrf->set('Imovel[DivulgacaoPlacaData]') ?>" value="<?=($this->val('Imovel.DivulgacaoPlacaData') == '' ? '' : date('Y-m-d', strtotime($this->val('Imovel.DivulgacaoPlacaData'))))?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </fieldset>
                                            </div>
                                        </div>
                                        <!-- Jornal-->
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <fieldset>
                                                    <legend>Jornal</legend>
                                                    <div class="row">
                                                        <div class="col-xs-2">
                                                            <div class="form-group<?php $e = $this->err('Imovel.DivulgacaoJornal') ?>">
                                                                <label class="radio radio-inline no-margin">
                                                                    <?php $v = $this->val('Imovel.DivulgacaoJornal'); ?>
                                                                    <input type="checkbox" name="<?= $this->csrf->set('Imovel[DivulgacaoJornal]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                                    <span>Imóvel está publicado no jornal?</span>
                                                                </label>
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-2">
                                                            <div class="form-group<?php $e = $this->err('Imovel.DivulgacaoJornalData') ?>">
                                                                <label for="EdDataPublicaJornal">Data da última publicação</label>
                                                                <input type="date" id="EdDataPublicaJornal" class="form-control"  name="<?= $this->csrf->set('Imovel[DivulgacaoJornalData]') ?>" value="<?=($this->val('Imovel.DivulgacaoJornalData') == '' ? '' : date('Y-m-d', strtotime($this->val('Imovel.DivulgacaoJornalData'))))?>">
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-2">
                                                            <div class="form-group<?php $e = $this->err('Imovel.DivulgacaoJornalValor') ?>">
                                                                <label for="EdValorAnuncio">Valor do anúncio</label>
                                                                <input type="number" id="EdValorAnuncio" class="form-control"  name="<?= $this->csrf->set('Imovel[DivulgacaoJornalValor]') ?>" value="<?=$this->val('Imovel.DivulgacaoJornalValor')?>">
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <div class="form-group<?php $e = $this->err('Imovel.DivulgacaoJornalAnuncio') ?>">
                                                                <label for="MmAnuncio">Texto do anúncio</label>
                                                                <textarea class="form-control ng-pristine ng-valid ng-touched" id="MmAnuncio"><?=$this->val('Imovel.DivulgacaoJornalAnuncio')?></textarea>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </fieldset>
                                            </div>
                                        </div>
                                        <!-- Redes sociais-->
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <fieldset>
                                                    <legend>Redes sociais</legend>
                                                    <div class="row">
                                                        <div class="col-xs-2">
                                                            <div class="form-group<?php $e = $this->err('Imovel.DivulgacaoFacebook') ?>">
                                                                <label class="radio radio-inline no-margin">
                                                                    <?php $v = $this->val('Imovel.DivulgacaoFacebook'); ?>
                                                                    <input type="checkbox" name="<?= $this->csrf->set('Imovel[DivulgacaoFacebook]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                                    <span>Possúi anúncio no Facebook?</span>
                                                                </label>
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <div class="form-group<?php $e = $this->err('Imovel.DivulgacaoFacebookUrl') ?>">
                                                                <label for="EdUrlFacebook">URL da publicação</label>
                                                                <div class="input-group">
                                                                    <input type="text" class="form-control ng-pristine ng-valid ng-touched" name="<?= $this->csrf->set('Imovel[DivulgacaoFacebookUrl]') ?>" value="<?=$this->val('Imovel.DivulgacaoFacebookUrl')?>" id="EdUrlFacebook">
                                                                    <span class="input-group-btn">
                                                                            <button class="btn btn-default" type="button" alt="Visualizar publicação" style="height: 32px;" onclick="AbreJanela('<?=$this->val('Imovel.DivulgacaoFacebookUrl')?>')"><i class="fa fa-facebook"></i></button>
                                                                        </span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-xs-2">
                                                            <div class="form-group<?php $e = $this->err('Imovel.DivulgacaoTwitter') ?>">
                                                                <label class="radio radio-inline no-margin">
                                                                    <?php $v = $this->val('Imovel.DivulgacaoTwitter'); ?>
                                                                    <input type="checkbox" name="<?= $this->csrf->set('Imovel[DivulgacaoTwitter]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                                    <span>Possúi anúncio no Twitter?</span>
                                                                </label>
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <div class="form-group<?php $e = $this->err('Imovel.DivulgacaoTwitterUrl') ?>">
                                                                <label for="EdUrlTwitter">URL da publicação</label>
                                                                <div class="input-group">
                                                                    <input type="text" class="form-control ng-pristine ng-valid ng-touched" id="EdUrlTwitter"  name="<?= $this->csrf->set('Imovel[DivulgacaoTwitterUrl]') ?>" value="<?=$this->val('Imovel.DivulgacaoTwitterUrl')?>">
                                                                    <span class="input-group-btn">
                                                                            <button class="btn btn-default" type="button" alt="Visualizar publicação" onclick="AbreJanela('<?=$this->val('Imovel.DivulgacaoTwitterUrl')?>')" style="height: 32px;"><i class="fa fa-twitter"></i></button>
                                                                        </span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </fieldset>
                                            </div>
                                        </div>
                                    </div>

                                    <!--<div class="tab-pane fade" id="ss4">&nbsp;</div>-->
                                </div>
                            </div>

                            <!--Tab Valores-->
                            <div class="tab-pane fade " id="s3">
                                <!-- Disponibilidade-->
                                <div class="row">
                                    <div style="margin-top: 15px; margin-bottom: 15px">
                                        <div class="col-xs-2">
                                            <label class="radio radio-inline no-margin">
                                                <?php $v = $this->val('Imovel.DisponivelAluguel'); ?>
                                                <input type="checkbox" name="<?= $this->csrf->set('Imovel[DisponivelAluguel]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                <span>Disponível para Aluguel</span>
                                            </label>
                                        </div>
                                        <div class="col-xs-2">
                                            <label class="radio radio-inline no-margin">
                                                <?php $v = $this->val('Imovel.DisponivelVenda'); ?>
                                                <input type="checkbox" name="<?= $this->csrf->set('Imovel[DisponivelVenda]') ?>" value="1" class="checkbox style-1" <?=$v=='1' ? 'checked' : '' ?>/>
                                                <span>Disponível para Venda</span>
                                            </label>
                                        </div>
                                    </div>
                                </div>

                                <!--Valores aluguel-->
                                <div class="row">
                                    <div class="col-xs-12 xs-sem-margem">
                                        <fieldset>
                                            <legend>Aluguel</legend>
                                            <div class="col-xs-12 xs-sem-margem">
                                                <div class="col-xs-2 xs-sem-margem">
                                                    <div class="form-group<?php $e = $this->err('Imovel.ValorAluguel') ?>">
                                                        <label for="EdValorAluguel">Valor aluguel</label>
                                                        <div class="input-group">
                                                            <span class="input-group-addon">R$</span>
                                                            <input type="text" id="EdValorAluguel" class="form-control"  name="<?= $this->csrf->set('Imovel[ValorAluguel]') ?>" value="<?=$this->val('Imovel.ValorAluguel')?>">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-1">
                                                    <div class="form-group<?php $e = $this->err('Imovel.PercentualAdministracao') ?>">
                                                        <label for="EdPercentAdm"> % Administração</label>
                                                        <div class="input-group">
                                                            <input  type="number" id="EdPercentAdm" class="form-control"  name="<?= $this->csrf->set('Imovel[PercentualAdministracao]') ?>" value="<?=$this->val('Imovel.PercentualAdministracao')?>">
                                                            <span class="input-group-addon">%</span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-2">
                                                    <div class="form-group<?php $e = $this->err('Imovel.ValorAdministracao') ?>">
                                                        <label for="EdValAdm">Valor administração</label>
                                                        <div class="input-group">
                                                            <span class="input-group-addon">R$</span>
                                                            <input  type="text" id="EdValAdm" class="form-control"  name="<?= $this->csrf->set('Imovel[ValorAdministracao]') ?>" value="<?=$this->val('Imovel.ValorAdministracao')?>">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-2">
                                                    <div class="form-group<?php $e = $this->err('Imovel.ValorRepasse') ?>">
                                                        <label for="EdValRepasse">Valor repasse</label>
                                                        <div class="input-group">
                                                            <span class="input-group-addon">R$</span>
                                                            <input  type="text" id="EdValRepasse" class="form-control" name="<?= $this->csrf->set('Imovel[ValorRepasse]') ?>" value="<?=$this->val('Imovel.ValorRepasse')?>">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </fieldset>
                                    </div>
                                </div>

                                <!--Valores venda-->
                                <div class="row">
                                    <div class="col-xs-12 xs-sem-margem">
                                        <fieldset>
                                            <legend>Venda</legend>
                                            <div class="col-xs-12 xs-sem-margem">
                                                <div class="col-xs-2 xs-sem-margem">
                                                    <div class="form-group<?php $e = $this->err('Imovel.ValorVenda') ?>">
                                                        <label for="EdValorVenda">Valor venda</label>
                                                        <div class="input-group">
                                                            <span class="input-group-addon">R$</span>
                                                            <input  type="text" id="EdValorVenda" class="form-control" name="<?= $this->csrf->set('Imovel[ValorVenda]') ?>" value="<?=$this->val('Imovel.ValorVenda')?>">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-1">
                                                    <div class="form-group<?php $e = $this->err('Imovel.PercentualComissao') ?>">
                                                        <label for="EdPercentComissao"> % Comissão</label>
                                                        <div class="input-group">
                                                            <input type="number" id="EdPercentComissao" class="form-control" name="<?= $this->csrf->set('Imovel[PercentualComissao]') ?>" value="<?=$this->val('Imovel.PercentualComissao')?>">
                                                            <span class="input-group-addon">%</span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-2">
                                                    <div class="form-group<?php $e = $this->err('Imovel.ValorComissaoVenda') ?>">
                                                        <label for="EdValComissao">Valor comissão</label>
                                                        <div class="input-group">
                                                            <span class="input-group-addon">R$</span>
                                                            <input  type="text" id="EdValComissao" class="form-control" name="<?= $this->csrf->set('Imovel[ValorComissaoVenda]') ?>" value="<?=$this->val('Imovel.ValorComissaoVenda')?>">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-2">
                                                    <div class="form-group<?php $e = $this->err('Imovel.ValorRepasseVenda') ?>">
                                                        <label for="EdValRepasseVenda">Valor repasse</label>
                                                        <div class="input-group">
                                                            <span class="input-group-addon">R$</span>
                                                            <input  type="text" id="EdValRepasseVenda" class="form-control" name="<?= $this->csrf->set('Imovel[ValorRepasseVenda]') ?>" value="<?=$this->val('Imovel.ValorRepasseVenda')?>">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-1">
                                                    <div class="form-group<?php $e = $this->err('Imovel.PercentualCaptacao') ?>">
                                                        <label for="EdPercentCaptacao"> % captação</label>
                                                        <div class="input-group">
                                                            <input type="number" id="EdPercentCaptacao" class="form-control" name="<?= $this->csrf->set('Imovel[PercentualCaptacao]') ?>" value="<?=$this->val('Imovel.PercentualCaptacao')?>">
                                                            <span class="input-group-addon">%</span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-2">
                                                    <div class="form-group<?php $e = $this->err('Imovel.ValorComissaoCaptador') ?>">
                                                        <label for="EdValCaptacao">Valor captação</label>
                                                        <div class="input-group">
                                                            <span class="input-group-addon">R$</span>
                                                            <input type="text" id="EdValCaptacao" class="form-control" placeholder=""  name="<?= $this->csrf->set('Imovel[ValorComissaoCaptador]') ?>" value="<?=$this->val('Imovel.ValorComissaoCaptador')?>">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </fieldset>
                                    </div>
                                </div>

                                <!--Outros valores-->
                                <div class="row">
                                    <div class="col-xs-12 xs-sem-margem">
                                        <fieldset>
                                            <legend>Outros valores</legend>
                                            <div class="col-xs-12 xs-sem-margem">
                                                <div class="col-xs-2 xs-sem-margem">
                                                    <div class="form-group<?php $e = $this->err('Imovel.ValorIptu') ?>">
                                                        <label for="EdValorIPTU">Valor IPTU</label>
                                                        <div class="input-group">
                                                            <span class="input-group-addon">R$</span>
                                                            <input type="text" id="EdValorIPTU" class="form-control"  name="<?= $this->csrf->set('Imovel[ValorIptu]') ?>" value="<?=$this->val('Imovel.ValorIptu')?>">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-2">
                                                    <div class="form-group<?php $e = $this->err('Imovel.ValorCondominio') ?>">
                                                        <label for="EdValorCondominio">Valor condomínio</label>
                                                        <div class="input-group">
                                                            <span class="input-group-addon">R$</span>
                                                            <input type="text" id="EdValorCondominio" class="form-control" name="<?= $this->csrf->set('Imovel[ValorCondominio]') ?>" value="<?=$this->val('Imovel.ValorCondominio')?>">
                                                        </div>

                                                    </div>
                                                </div>
                                                <div class="col-xs-4">
                                                    <div class="form-group<?php $e = $this->err('Imovel.DescricaoValoresCondominio') ?>">
                                                        <label for="MmDescricaoValCond">Descrição de valores do condomínio</label>
                                                        <textarea class="form-control ng-pristine ng-valid ng-touched no-resize-textarea" id="MmDescricaoValCond"><?=$this->val('Imovel.DescricaoValoresCondominio')?></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </fieldset>
                                    </div>
                                </div>
                            </div>

                            <!--Tab Ligações telefonicas-->
                            <div class="tab-pane fade " id="s4">
                                <div class="row" style="margin-top: 15px; margin-bottom: 15px">
                                    <div class="col-xs-9">
                                        <table id="dt_basic" class="table data-table table-striped table-bordered table-hover" width="100%">
                                            <thead>
                                            <tr>
                                                <th data-class="expand"><i class="fa fa-fw fa-cloud  text-muted hidden-md hidden-sm hidden-xs"></i> Imóvel nº site</th>
                                                <th data-hide="phone"><i class="fa fa-fw fa-building text-muted hidden-md hidden-sm hidden-xs"></i> Imóvel</th>
                                                <th data-hide="phone" style="text-align: center">Interessado em</th>
                                                <th>Nome cliente</th>
                                                <th><i class="fa fa-fw fa-phone text-muted hidden-md hidden-sm hidden-xs"></i> Telefone cliente</th>
                                                <th>Tipo Mídia</th>
                                                <th data-hide="phone,tablet" style="text-align: center">Imóvel cadastrado</th>
                                                <th data-hide="phone,tablet" style="text-align: center">Cliente cadastrado</th>
                                                <th data-hide="phone,tablet" style="text-align: center">Encerrado</th>
                                                <th data-hide="phone,tablet">
                                                    <i class="fa fa-fw fa-calendar hidden-md hidden-sm hidden-xs"></i> Data cadastro</th>
                                            </tr>
                                            </thead>

                                            <?php if($all = $this->model->LigacoesTelefonicas->all()): //echo '<pre>';var_dump($all);?>
                                                <tbody>
                                                <?php foreach ($all as $i => $o): $i++; ?>
                                                    <tr class="row-data <?=($o->Encerrado == 1 ? 'danger' : 'success' )?>">
                                                        <td><?=$o->NumSiteImovel?></td>
                                                        <td><?=$o->NomeImovel?></td>
                                                        <td style="text-align: center">
                                                            <?php
                                                            if ($o->InteressadoEm == 'A')
                                                                echo '<span class="label label-primary">Aluguel</span>';
                                                            else
                                                                echo '<span class="label label-info">Venda</span>';
                                                            ?>
                                                        </td>
                                                        <td><?=$o->NomeCliente?></td>
                                                        <td><?=$o->NumSiteImovel?></td>
                                                        <td><?php if (@$o->TipoMidia->Nome <> null) echo @$o->TipoMidia->Nome;?></td>
                                                        <td style="text-align: center">
                                                            <?php
                                                            if ($o->ImovelCadastrado)
                                                                echo '<span class="label label-success">Sim</span>';
                                                            else
                                                                echo '<span class="label label-danger">Não</span>';

                                                            ?>
                                                        </td>
                                                        <td style="text-align: center">
                                                            <?php
                                                            if ($o->ClienteCadastrado)
                                                                echo '<span class="label label-success">Sim</span>';
                                                            else
                                                                echo '<span class="label label-danger">Não</span>';

                                                            ?>
                                                        </td>
                                                        <td style="text-align: center">
                                                            <?php
                                                            if ($o->Encerrado)
                                                                echo '<span class="label label-danger">Sim</span>';
                                                            else
                                                                echo '<span class="label label-success">Não</span>';

                                                            ?>
                                                        </td>
                                                        <td><?=date('d/m/Y H:i', strtotime($o->DataCriacao));?></td>
                                                    </tr>
                                                <?php endforeach; ?>
                                                </tbody>
                                            <?php else: ?>
                                                <tbody>
                                                <tr>
                                                    <td colspan="10" class="sem-registro"><i class="fa fa-info-circle"></i> Esse imóvel ainda não possuí ligações telefônicas relacionadas a ele. </td>
                                                </tr>
                                                </tbody>
                                            <?php endif; ?>



                                        </table>
                                    </div>
                                    <div class="col-xs-3">
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h3 class="panel-title">Ligações recebidas por mês</h3>
                                            </div>
                                            <div class="panel-body">
                                                <!--<canvas id="bar" class="chart chart-bar" chart-data="dataBarra" chart-labels="labelsBarra"></canvas>-->
                                                <div style="display: block">
                                                    <canvas id="myChart" ></canvas>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h3 class="panel-title">Ligações recebidas por mídia</h3>
                                            </div>
                                            <div class="panel-body">
                                                <!--<canvas id="doughnut" class="chart chart-doughnut" chart-data="dataPizza" chart-labels="labelsPizza" chart-legend="true"></canvas>-->
                                                <div style="display: block">
                                                    <canvas id="myChart1" ></canvas>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!--Tab Mapa-->
                            <div class="tab-pane fade in " id="s5">
                                <div class="row" *ngIf="mapaAtivo">
                                    <fieldset>
                                        <div class="col-sm-12">
                                            <div class="map"></div>
                                        </div>
                                    </fieldset>
                                </div>
                                <?php if ($this->val('Imovel.MapaLatitude') === '') : ?>
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="alert alert-info alert-block">
                                                <a class="close" data-dismiss="alert" href="#">×</a>
                                                <h4 class="alert-heading">Aviso!</h4>
                                                Localização ainda não disponível. Cadastre as informações sobre o endereço do imóvel.
                                            </div>
                                        </div>
                                    </div>
                                <?php else : ?>
                                    <div id="map" style="height: 400px; width: 100%;"></div>
                                <?php endif; ?>
                            </div>

                            <!--Tab Contratos de aluguel-->
                            <div class="tab-pane fade" id="s6">
                                <div class="row">
                                    <div class="col-xs-12" style="text-align: right">
                                        <?php

                                        ?>

                                    </div>
                                </div>

                                <div class="row" style="margin-top: 15px; margin-bottom: 15px">
                                    <div class="col-xs-12">
                                        <div class="row">
                                            <div class="col-xs-12" style="text-align: right; margin-bottom: 7px">
                                                <?php
                                                if($all = $this->model->Contratos->all()) {
                                                    $disabledbutton = 0;

                                                    foreach ($all as $i => $o): $i++;
                                                        if ($o->Ativo) $disabledbutton++;
                                                    endforeach;

                                                    if ($disabledbutton > 0) {
                                                        echo '<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModalAlugarImovel" onclick="ModalAlugarImovel()" id="BtNovoContratoAluguel" disabled="disabled"><i class="fa fa-plus-square"></i> Novo contrato de aluguel</button>';
                                                    } else {
                                                        echo '<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModalAlugarImovel" onclick="ModalAlugarImovel()" id="BtNovoContratoAluguel"><i class="fa fa-plus-square"></i> Novo contrato de aluguel</button>';
                                                    }
                                                } else {
                                                    if (($this->val('Imovel.Situacao') === 'Alugado') || ($this->val('Imovel.Situacao') === 'Vendido') || ($this->val('Imovel.Situacao') === 'Reservado') || ($this->val('Imovel.Situacao') === 'Negociação'))
                                                        $StatusBotaoAluguel = 'disabled="disabled"';
                                                    else
                                                        $StatusBotaoAluguel = '';

                                                    echo '<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModalAlugarImovel" onclick="ModalAlugarImovel()" id="BtNovoContratoAluguel"' . $StatusBotaoAluguel . '><i class="fa fa-plus-square"></i>Novo contrato de aluguel</button>';
                                                }
                                                ?>

                                            </div>
                                        </div>
                                        <table id="TbContratosAluguel" class="table data-table table-striped table-bordered table-hover" width="100%">
                                            <thead>
                                            <tr>
                                                <th data-class="expand" class="centralizado"><i class="fa fa-fw fa-file-excel-o  text-muted hidden-md hidden-sm hidden-xs "></i> Número contrato</th>
                                                <th data-hide="phone" class="centralizado"><i class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i> Data início</th>
                                                <th data-hide="phone" class="centralizado"><i class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i> Data fim</th>
                                                <th class="centralizado">Tempo de contrato</th>
                                                <th class="centralizado"><i class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i> Dia vencimento</th>
                                                <th class="centralizado">Renovação</th>
                                                <th data-hide="phone,tablet" class="centralizado">Data renovação</th>
                                                <th data-hide="phone,tablet" class="centralizado">Ativo</th>
                                                <th data-hide="phone,tablet" class="centralizado">Data cadastro</th>
                                            </thead>

                                            <?php if($all = $this->model->Contratos->all()): //echo '<pre>';var_dump($all);?>
                                                <tbody>
                                                <?php foreach ($all as $i => $o): $i++; ?>
                                                    <tr class="row-data <?php echo ($o->Ativo ? 'success' : ''); ?>">
                                                        <td class="cell-link centralizado"><?=str_pad($o->NumeroContrato, 5, '0', STR_PAD_LEFT)?></td>
                                                        <td class="cell-link centralizado"><?=date('d/m/Y', strtotime($o->DataInicio));?></td>
                                                        <td class="cell-link centralizado"><?=date('d/m/Y', strtotime($o->DataFim));?></td>
                                                        <td class="cell-link centralizado"><?=$o->TempoContrato?></td>
                                                        <td class="cell-link centralizado"><?=str_pad($o->DiaVencimento,2,'0',STR_PAD_LEFT)?></td>
                                                        <td class="cell-link centralizado">
                                                            <?php
                                                            if ($o->Renovacao)
                                                                echo '<span class="label label-success">Sim</span>';
                                                            else
                                                                echo '<span class="label label-danger">Não</span>';
                                                            ?>
                                                        </td>
                                                        <td class="cell-link centralizado"><?=$o->RenovacaoData?></td>
                                                        <td class="cell-link centralizado">
                                                            <?php
                                                            if ($o->Ativo)
                                                                echo '<span class="label label-success">Sim</span>';
                                                            else
                                                                echo '<span class="label label-danger">Não</span>';

                                                            ?>
                                                        </td>
                                                        <td class="cell-link centralizado"><?=date('d/m/Y H:i', strtotime($o->DataCriacao));?></td>
                                                    </tr>
                                                <?php endforeach; ?>
                                                </tbody>
                                            <?php else: ?>
                                                <tbody>
                                                <tr>
                                                    <td colspan="9" class="sem-registro"><i class="fa fa-info-circle"></i> Esse imóvel ainda não possuí contratos de aluguel. </td>
                                                </tr>
                                                </tbody>
                                            <?php endif; ?>

                                        </table>
                                    </div>
                                </div>
                            </div>

                            <!--Tab Contratos de venda-->
                            <div class="tab-pane fade" id="s7">
                                <div class="row" style="margin-top: 15px; margin-bottom: 15px">
                                    <div class="col-xs-12">
                                        <div class="row">
                                            <div class="col-xs-12" style="text-align: right; margin-bottom: 7px">
                                                <?php
                                                if (($this->val('Imovel.Situacao') === 'Alugado') || ($this->val('Imovel.Situacao') === 'Vendido') || ($this->val('Imovel.Situacao') === 'Reservado'))
                                                    $StatusBotaoAluguel = 'disabled="disabled"';
                                                else
                                                    $StatusBotaoAluguel = '';

                                                echo '<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModalAddContratoVenda" onclick="ModalAddContrato()" id="BtNovoContratoVenda"' . $StatusBotaoAluguel . '><i class="fa fa-plus-square"></i> Nova proposta</button>';
                                                ?>

                                            </div>
                                        </div>
                                        <table id="TbPropostasVenda" class="table data-table table-striped table-bordered table-hover" width="100%">
                                            <thead>
                                            <tr>
                                                <th data-class="expand">Nome</th>
                                                <th data-class="expand" class="centralizado">Situação</th>
                                                <th class="centralizado">Forma de pagamento</th>
                                                <th class="centralizado"><i class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i> Data validade</th>
                                                <th class="centralizado"><i class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i> Data possível entrada</th>
                                                <th class="centralizado">Parcelas entrada</th>
                                                <th class="centralizado">Parcelas financiamento</th>
                                                <th>Valor entrada</th>
                                                <th>Valor financiamento</th>
                                                <th class="centralizado"> <i class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i> Data emissão</th>
                                            </tr>
                                            </thead>

                                            <?php if($all = $this->model->PropostasVenda->all()): //echo '<pre>'; var_dump($all) ?>
                                                <tbody>
                                                <?php foreach ($all as $i => $o): $i++; ?>
                                                    <?php
                                                    $Color = '';
                                                    if ($o->FormaPagamentoEntrada == 'CHEQUE')
                                                        $Color = 'bg-color-greenDark';
                                                    else if ($o->FormaPagamentoEntrada == 'DINHEIRO')
                                                        $Color = 'bg-color-blueDark';
                                                    else if ($o->FormaPagamentoEntrada == 'BOLETO')
                                                        $Color = 'bg-color-orangeDark';
                                                    else if ($o->FormaPagamentoEntrada == 'DEBITO_CONTA')
                                                        $Color = 'bg-color-teal';
                                                    else if ($o->FormaPagamentoEntrada == 'FINANCIAMENTO')
                                                        $Color = 'bg-color-pinkDark';
                                                    else if ($o->FormaPagamentoEntrada == 'NOTA_PROMISSORIA')
                                                        $Color = 'bg-color-teal';

                                                    $Label = '';

                                                    if (@$o->StatusProposta->Nome == 'Aberta')
                                                        $Label = 'primary';
                                                    else if (@$o->StatusProposta->Nome == 'Recusada')
                                                        $Label = 'danger';
                                                    else if (@$o->StatusProposta->Nome == 'Aceita')
                                                        $Label = 'success';
                                                    else
                                                        $Label = 'default';

                                                    ?>
                                                    <tr class="row-data">
                                                        <td class=""><?=$o->Nome ? '<a rel="tooltip" data-placement="right" data-original-title="<i class=\'fa fa-info-circle text-primary\'></i> Clique aqui para abrir os detalhes dessa proposta" data-html="true" target="_blank" href='.backend_url('/central-vendas/editar/'.$o->Id).'>'.$o->Nome.'</a>' : '' ?></td>
                                                        <td class=""><span class="center-block padding-5 label label-<?=$Label?>"><?=$o->StatusProposta->Nome?></span></td>
                                                        <td class="centralizado"><span class="center-block padding-5 label <?=$Color?> txt-color-white"><?=str_replace('_',' ',mb_convert_case($o->FormaPagamentoEntrada, MB_CASE_TITLE, 'UTF-8'))?></span></td>
                                                        <td class="centralizado"><?=($o->DataValidade == '' ? '' : date('d/m/Y',strtotime($o->DataValidade)))?></td>
                                                        <td class="centralizado"><?=($o->DataPossivelEntrada == '' ? '' : date('d/m/Y',strtotime($o->DataPossivelEntrada)))?></td>
                                                        <td class="centralizado"><span class="badge bg-color-magenta"><?=str_pad($o->NumParcelasEntrada, 3, "0", STR_PAD_LEFT)?></span></td>
                                                        <td class="centralizado"><span class="badge bg-color-purple"><?=str_pad($o->NumParcelasFinanciamento, 3, "0", STR_PAD_LEFT)?></span></td>
                                                        <td class=""><?='R$: '.number_format($o->ValorEntrada,2,',', '.');?></td>
                                                        <td class=""><?='R$: '.number_format($o->ValorFinanciado,2,',', '.');?></td>
                                                        <td class="centralizado"><?=($o->DataEmissao == '' ? '' : date('d/m/Y',strtotime($o->DataEmissao)))?></td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            <?php else: ?>
                                                <tbody>
                                                <tr>
                                                    <td colspan="9" class="sem-registro"><i class="fa fa-info-circle"></i> Esse imóvel ainda não possuí propostas de venda. </td>
                                                </tr>
                                                </tbody>
                                            <?php endif; ?>

                                        </table>
                                    </div>
                                </div>
                            </div>

                            <!--Tab Anexos-->
                            <div class="tab-pane fade" id="s8">

                                <div class="row">
                                    <div class="col-xs-12">

                                        <div action="upload.php" class="dropzone" id="mydropzoneImoveis">
                                            <input type="hidden" name="ImovelId" id="ImovelId" value="<?=$this->val('Imoveis.Id')?>">
                                        </div>

                                    </div>
                                </div>
                                <div class="row" style="margin-top: 15px">
                                    <div class="col-xs-12" id="TunbNails">
                                        <div id="lightgallery">
                                            <?php if($all = $this->Anexos): ?>
                                                <?php foreach ($all as $o): $i++; ?>

                                                    <a href="<?=$o?>">
                                                        <img src="<?=$o?>" width="100px" height="100px;" style="margin-right: 7px; margin-top: 10px" />
                                                    </a>

                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-12">
                                    <?=$this->actions('remove | save | savenew | saveclose | close | new')?>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- end widget content -->

            </div>
            <!-- end widget div -->

        </div>
        <!-- end widget -->

    </article>
    <!-- WIDGET END -->

</div>

<!-- end row -->

<!--  Modal pessoas  -->
<div class="modal fade" id="myModalAddPessoas" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="myModalLabel">Adicionar pessoas ao imóvel</h4>
            </div>
            <form name="form-modalAddPessoas" id="form-modalAddPessoas" class="form-modalAddPessoas">
                <div class="modal-body">
                    <div class="row">
                        <input type="hidden" id="EdIdImovel" name="EdIdImovel" value="<?=$this->val('Imovel.Id')?>">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="EdNomePessoa">Nome do locatário</label>
                                <div class="input-group">
                                    <input type="hidden" id="EdIdPessoaAddImovel" name="EdIdPessoaAddImovel" value="">
                                    <input class="form-control ui-autocomplete-input" id="EdNomePessoaAddImovel" name="EdNomePessoaAddImovel" style="text-transform: uppercase;" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true" type="text">
                                    <span class="input-group-btn">
                                            <button type="button" class="btn btn-default" style="height: 32px;"><i class="fa fa-search"></i></button>
                                        </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-10">
                                    <div class="form-group">
                                        <label for="CbTipoVinculo">Tipo de vinculo</label>
                                        <select class="form-control" name="CbTipoVinculo" id="CbTipoVinculo">
                                            <option value="">-- Tipo de vinculo --</option>
                                            <?php foreach ($this->model->TipoVinculos() as $obj): $_v = $obj->Id; ?>
                                                <option value="<?=$_v?>"<?=($v==$_v ? ' selected' : '')?>><?=$obj->Nome?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label for="EdPercentual">Percentual</label>
                                        <input type="number" id="EdPercentual" class="form-control" placeholder="" name="EdPercentual" value="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">

                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> <u>S</u>alvar</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        <i class="fa fa-close"></i> <u>F</u>echar
                    </button>

                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--  Modal caracteristicas avançadas  -->
<div class="modal fade" id="myModalAddCaracteristicas" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="myModalLabel">Adicionar características avançadas</h4>
            </div>
            <form name="form-modalAddCaracteristica" id="form-modalAddCaracteristica" class="form-modalAddCaracteristica">
                <div class="modal-body">
                    <div class="row">
                        <input type="hidden" id="EdIdImovelCaracteristicas" name="EdIdImovelCaracteristicas" value="<?=$this->val('Imovel.Id')?>">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="CbCaracteristica">Características</label>
                                <select class="form-control" name="CbCaracteristica" id="CbCaracteristica">
                                    <option value="">-- Características --</option>
                                    <?php foreach ($this->model->Caracteristicas() as $obj): $_v = $obj->Id; ?>
                                        <option value="<?=$_v?>"<?=($v==$_v ? ' selected' : '')?>><?=$obj->Nome?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="EdNomeCaracteristicas">Descrição</label>
                                <textarea class="form-control" id="EdDescricaoCaracteristica" name="EdDescricaoCaracteristica"></textarea>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-4">

                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> <u>S</u>alvar</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        <i class="fa fa-close"></i> <u>F</u>echar
                    </button>

                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--  Modal alugar Imovel-->
<div class="modal fade" id="myModalAlugarImovel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="myModalLabel">Alugar imóvel</h4>
            </div>
            <form class="form-modalAddContratoAluguel" id="form-modalAddContratoAluguel" name="form-modalAddContratoAluguel">
                <div class="modal-body">

                    <div class="row">
                        <input type="hidden" id="EdIdImovel" name="EdImovelAlugar" value="<?=$this->val('Imovel.Id')?>">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="EdNomePessoa">Nome do locatário</label>
                                <div class="input-group">
                                    <input type="hidden" id="EdIdPessoaAlugar" name="EdIdPessoaAlugar" value="">
                                    <input class="form-control ui-autocomplete-input" id="EdNomePessoaAlugar" name="EdNomePessoaAlugar" style="text-transform: uppercase;" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true" type="text">
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-default" style="height: 32px;"><i class="fa fa-search"></i></button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="well well-sm well-primary">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="EdDataInicioContrato">Fim do contrato</label>
                                            <input type="date" id="EdDataInicioContrato" class="form-control" placeholder="" name="EdDataInicioContrato" value="">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="EdDuracaoContrato">Duração</label>
                                            <input type="number" id="EdDuracaoContrato" class="form-control" placeholder="" name="EdDuracaoContrato" value="">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="EdFimContrato">Fim do contrato</label>
                                            <input type="date" id="EdFimContrato" class="form-control" placeholder="" name="EdFimContrato" value="">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="EdDiaVencimento">Vencimento</label>
                                            <input type="number" id="EdDiaVencimento" class="form-control" placeholder="" name="EdDiaVencimento" value="?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <br>
                                        <label class="radio radio-inline no-margin">
                                            <input type="checkbox" name="CkAtivoContratoAlguel"  value="1" class="checkbox style-1" checked/>
                                            <span>Ativo</span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">

                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> <u>S</u>alvar</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        <i class="fa fa-close"></i> <u>F</u>echar
                    </button>

                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--Modal contrato de venda-->
<div class="modal fade" id="myModalAddContratoVenda" tabindex="-1" role="dialog" aria-labelledby="myModalAddContratoVenda" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="myModalLabel">Vender imóvel</h4>
            </div>
            <form class="form-modalAddContratoVenda" id="form-modalAddContratoVenda" method="post">
                <div class="modal-body">

                    <input type="hidden" id="EdIdImovel" name="EdIdImovel" value="<?=$this->val('Imoveis.Id')?>">
                    <fieldset>
                        <legend>Dados das partes</legend>

                        <div class="alert alert-info fade in" id="MensagemAddPessoas" style="display: none">
                            <button class="close" data-dismiss="alert">
                                ×
                            </button>
                            <strong>Info!</strong> Você deve adicionar as partes da proposta antes de salvar
                        </div>

                        <div class="row">

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">Papel</label>
                                    <select class="form-control" name="" id="CbTipoPartes">
                                        <option value="">-- Papéis --</option>
                                        <?php foreach ($this->model->TiposParteProposta() as $obj): $_v = $obj->Id; ?>
                                            <option value="<?=$_v?>"><?=$obj->Nome?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="form-group<?php $e = $this->err('CentralVendas.PessoaId') ?>">
                                    <label for="EdNomePessoa">Selecione o comprador e clique em adicionar</label>
                                    <div class="input-group">
                                        <input type="hidden" id="EdIdPessoa" name="" value="">
                                        <input class="form-control ui-autocomplete-input" id="EdNomePessoa" name="EdNomePessoa" style="text-transform: uppercase;" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true" type="text" autofocus>
                                        <span class="input-group-btn">
                                        <button type="button" class="btn btn-primary" style="height: 32px;"><i class="fa fa-search"></i></button>
                                    </span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-1">
                                <button type="button" id="BtAddPessoasVenda" class="btn btn-primary" style="height: 32px; margin-top: 23px; margin-left: -16px;"><i class="fa fa-plus"></i></button>
                            </div>
                        </div>
                        <div class="row" id="PessoasAdd" style="margin-bottom: 15px"></div>
                    </fieldset>

                    <fieldset>
                        <legend>Valores</legend>
                        <div class="alert alert-info fade in" id="MensagemAddPartes" style="display: none">
                            <button class="close" data-dismiss="alert">
                                ×
                            </button>
                            <strong>Info!</strong> Você deve adicionar os valores da proposta antes de salvar
                        </div>

                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label">Tipo</label>
                                    <select class="form-control" name="" id="CbTipoPagamento">
                                        <option value="">-- Tipo --</option>
                                        <?php foreach ($this->model->TiposPagamento() as $obj): $_v = $obj->Id; ?>
                                            <option value="<?=$_v?>"><?=$obj->Descricao?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="EdValor">Valor</label>
                                    <div class="input-group">
                                        <span class="input-group-addon">R$</span>
                                        <input id="EdValor" class="form-control"  value="" type="text">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label for="EdQntParcela">Parcelas</label>
                                    <input id="EdQntParcela" class="form-control"  value="" type="number">
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label">Periodicidade</label>
                                    <select class="form-control" name="" id="CbPeriodicidade">
                                        <option value="">-- Periodicidade  --</option>
                                        <option value="UNICO">Único</option>
                                        <option value="SEMESTRAL">Semanal</option>
                                        <option value="QUINZENAL">Quinzenal</option>
                                        <option value="MENSAL">Mensal</option>
                                        <option value="BIMESTRAL">Bimestral</option>
                                        <option value="TRIMESTRAL">Trimestral</option>
                                        <option value="QUADRIMETRAL">Quadrimestral</option>
                                        <option value="QUIMESTRAL">Quimestral</option>
                                        <option value="SEMESTRAL">Semestral</option>
                                        <option value="ANUAL">Anual</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4" style="width:166px">
                                <div class="form-group">
                                    <label for="EdDataVencimento">Data vencimento</label>
                                    <input id="EdDataVencimento" class="form-control"  value="" type="date">
                                </div>
                            </div>
                            <div class="col-md-3" style="width:173px">
                                <div class="form-group">
                                    <label class="control-label">Atualização monetária</label>
                                    <select class="form-control" name="" id="CbAtulizacaoMonetaria">
                                        <option value="">-- Atu. monentária --</option>
                                        <option value="FIXA">Fixa</option>
                                        <option value="REAJUSTAVEL">Reajustavel</option>
                                        <option value="IRREAJUSTAVEL">Irreajustavel</option>
                                        <option value="FIXA_IRREAJUSTAVEL">Fixa e Irreajustavel</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-2" style="width:196px;">
                                <div class="form-group">
                                    <label class="control-label">Forma de pagamento</label>
                                    <select class="form-control" name="" id="CbFormaPagamento">
                                        <option value="">-- Forma de pagamento --</option>
                                        <option value="DINHEIRO">Dinheiro</option>
                                        <option value="CHEQUE">Cheque</option>
                                        <option value="BOLETO">Boleto</option>
                                        <option value="DEBITO_CONTA">Débito em conta</option>
                                        <option value="FINANCIAMENTO">Financiamento</option>
                                        <option value="NOTA_PROMISSORIA">Nova promissória</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-1">
                                <button type="button" id="BtAddParcelas" class="btn btn-primary" style="height: 32px; margin-top: 23px; margin-left: -16px;"><i class="fa fa-plus"></i></button>
                            </div>
                        </div>
                        <div id="ValoresAdd"></div>
                    </fieldset>



                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" type="submit" name="_save" value="2"><i class="fa fa-save"></i> <u>S</u>alvar</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        <i class="fa fa-close"></i> <u>F</u>echar
                    </button>

                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>

    function ModalAdicionarPessoas() {
        $("#EdIdPessoaAddImovel").val("");
        $("#EdNomePessoaAddImovel").val("");
        $("#EdPercentual").val("");
        $("#CbTipoVinculo").val("");
        $('#CbTipoVinculo :nth-child(0)').prop('selected', true);
    }

    function ModalAdicionarCaracteristica() {
        $("#EdDescricaoCaracteristica").val("");
        $('#CbCaracteristica :nth-child(0)').prop('selected', true);
    }

    function FechaModalAdicionarPessoas()   {
        $('#myModalAddPessoas').modal('hide');
    }

    function ModalAlugarImovel() {
        var now = new Date();

        var day = ("0" + now.getDate()).slice(-2);
        var month = ("0" + (now.getMonth() + 1)).slice(-2);

        var today = now.getFullYear()+"-"+(month)+"-"+(day);


        $("#EdIdPessoaAlugar").val("");
        //$("#EdIdImovel").val("");
        $("#EdNomePessoaAlugar").val("");
        $("#EdDataInicioContrato").val(today);
        $("#EdDuracaoContrato").val("12");
        $("#EdFimContrato").val("");
        $("#EdDiaVencimento").val(day);

        now = addMonths(new Date(), 12);
        var day = ("0" + now.getDate()).slice(-2);
        var month = ("0" + (now.getMonth() + 1)).slice(-2);

        var datafinal = now.getFullYear()+"-"+(month)+"-"+(day);
        $("#EdFimContrato").val(datafinal);

        $("#EdNomePessoaAlugar").focus();
    }

    function ModalAddContrato() {
        $('#EdIdPessoa').val("");
        $('#EdNomePessoa').val("");
        $('#CbTipoPartes').val("");
        $("select[id=CbTipoPartes]").val($("select[id=CbTipoPartes] option:first-child").val());

        $('#EdValor').val("");
        $('#EdQntParcela').val("");
        $('#EdDataVencimento').val("");
        $("select[id=CbTipoPagamento]").val($("select[id=CbTipoPagamento] option:first-child").val());
        $("select[id=CbPeriodicidade]").val($("select[id=CbPeriodicidade] option:first-child").val());
        $("select[id=CbAtulizacaoMonetaria]").val($("select[id=CbAtulizacaoMonetaria] option:first-child").val());
        $("select[id=CbFormaPagamento]").val($("select[id=CbFormaPagamento] option:first-child").val());
        $("#PessoasAdd").html("");
        $("#ValoresAdd").html("");

    }





</script>