<!-- row -->
<div class="row">

    <!-- NEW WIDGET START -->
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <!-- Widget ID (each widget will need unique ID)-->
        <div
                class="jarviswidget"
                id="wid-id-0"
                data-widget-colorbutton="false"
                data-widget-editbutton="false"
                data-widget-deletebutton="false"
                data-widget-custombutton="false"
        >
            <!-- widget options:
                usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                data-widget-colorbutton="false"
                data-widget-editbutton="false"
                data-widget-togglebutton="false"
                data-widget-deletebutton="false"
                data-widget-fullscreenbutton="false"
                data-widget-custombutton="false"
                data-widget-collapsed="true"
                data-widget-sortable="false"

            -->
            <header>
                <span class="widget-icon"> <i class="fa fa-list"></i> </span>
                <h2>Imóveis cadastrados</h2>
            </header>

            <!-- widget div-->
            <div>

                <!-- widget edit box -->
                <div class="jarviswidget-editbox">
                    <!-- This area used as dropdown edit box -->
                    <input class="form-control" type="text">
                </div>
                <!-- end widget edit box -->

                <!-- widget content -->
                <div class="widget-body wsgi-data no-padding">

                    <div class="dt-toolbar toolbar-actions">
                        <div class="col-sm-6">
                            <div class="toolbar-actions-text">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="control-actions">
                                <?=$this->actions();?>
                            </div>
                        </div>
                    </div>

                    <table id="dt_basic" class="table data-table table-striped table-bordered table-hover data-sort" width="100%">
                        <thead>
                        <tr>
                            <th data-hide="phone">
                                <div class="checkbox checkbox-danger">
                                    <input type="checkbox" name="dsd" id="toggle-all">
                                    <label for="toggle-all">
                                        <i class="fa fa-hashtag"></i>
                                    </label>
                                </div>
                            </th>
                            <th data-class="expand" class="centralizado"><i class="fa fa-fw fa-folder text-muted hidden-md hidden-sm hidden-xs"></i> Pasta / Contrato</th>
                            <th data-class="expand" class="centralizado"><i class="fa fa-fw fa-cloud text-muted hidden-md hidden-sm hidden-xs"></i> Nº Site</th>
                            <th>Disponibilidade</th>
                            <th>Situação</th>
                            <th data-class="expand"><i class="fa fa-fw fa-building text-muted hidden-md hidden-sm hidden-xs"></i> Empreendimento</th>
                            <th data-class="expand"><i class="fa fa-fw fa-map-marker  text-muted hidden-md hidden-sm hidden-xs"></i> Logradouro</th>
                            <th data-class="expand"><i class="fa fa-fw fa-map-marker  text-muted hidden-md hidden-sm hidden-xs"></i> Bairro</th>
                            <th data-hide="phone" class="centralizado"><i class="fa fa-fw fa-map-marker text-muted hidden-md hidden-sm hidden-xs"></i> Quadra</th>
                            <th data-hide="phone" class="centralizado"><i class="fa fa-fw fa-map-marker text-muted hidden-md hidden-sm hidden-xs"></i> Lote</th>
                            <th data-hide="phone" class="centralizado"><i class="fa fa-fw fa-map-marker text-muted hidden-md hidden-sm hidden-xs"></i> Número</th>
                            <th data-hide="phone"><i class="fa fa-fw fa-map-marker text-muted hidden-md hidden-sm hidden-xs"></i> Cidade</th>
                            <th data-hide="phone" class="centralizado"><i class="fa fa-fw fa-map-marker text-muted hidden-md hidden-sm hidden-xs"></i> UF</th>
                            <th data-hide="phone" class="centralizado"><i class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i> Data cadastro</th>

                        </tr>
                        </thead>

                        <?php if($all = $this->model->all()): //echo '<pre>'; var_dump($all) ?>
                            <tbody>
                            <?php foreach ($all as $i => $o): $i++; ?>
                                <tr class="row-data">
                                    <td class="cell-check"><?=$this->checks($i, $o->Id);?></td>
                                    <td class="cell-link centralizado"><?=$o->Pasta?></td>
                                    <td class="cell-link centralizado"><?=$o->NumSite?></td>
                                    <td class="cell-link">
                                        <?php
                                        $sDisponivelPara = '';
                                        if ($o->DisponivelVenda == 1)
                                            $sDisponivelPara = '<span class="label bg-color-blueDark txt-color-white">Venda</span> &nbsp;';

                                        if ($o->DisponivelAluguel == 1)
                                            $sDisponivelPara .= '<span class="label bg-color-blue txt-color-white">Aluguel</span>';

                                        echo $sDisponivelPara;

                                        ?>
                                    </td>
                                    <td class="cell-link">
                                        <?php
                                        $sSituacao = '';
                                        if ($o->Situacao == 'Alugado')   $sSituacao = '<span class="center-block padding-5 label label-primary">Alugado</span>';
                                        if ($o->Situacao == 'Livre')     $sSituacao = '<span class="center-block padding-5 label label-success">Livre</span>';
                                        if ($o->Situacao == 'Vendido')   $sSituacao = '<span class="center-block padding-5 label label-danger">Vendido</span>';
                                        if ($o->Situacao == 'Reservado') $sSituacao = '<span class="center-block padding-5 label label-warning">Reservado</span>';
                                        if ($o->Situacao == 'Negociação') $sSituacao = '<span class="center-block padding-5 label bg-color-purple txt-color-white">Negociação</span>';

                                        echo $sSituacao;

                                        ?>
                                    </td>
                                    <td class="cell-link1">
                                        <?=$o->Empreendimento ? '<a rel="tooltip" data-placement="right" data-original-title="<i class=\'fa fa-info-circle text-primary\'></i> Clique aqui para abrir esse empreendimento em uma nova aba" data-html="true" target="_blank" href='.backend_url('/empreendimentos/editar/'.$o->Empreendimento->Id).'>'.$o->Empreendimento->Nome.'</a>' : '' ?>
                                    </td>
                                    <td class="cell-link"><?php if ($o->Endereco <> null) echo $o->Endereco->Logradouro; ?></td>
                                    <td class="cell-link"><?php if ($o->Endereco <> null) echo $o->Endereco->Bairro; ?></td>
                                    <td class="cell-link centralizado"><?=@$o->Endereco->Quadra; ?></td>
                                    <td class="cell-link centralizado"><?=@$o->Endereco->Lote; ?></td>
                                    <td class="cell-link centralizado"><?=@$o->Endereco->Numero; ?></td>
                                    <td class="cell-link"><?=@$o->Endereco->Cidade->Nome; ?></td>
                                    <td class="cell-link centralizado" style=""><?php if ($o->Endereco <> null) echo $o->Endereco->Cidade->Estado->Uf; ?></td>
                                    <td class="cell-link centralizado"><?=date('d/m/Y H:i', strtotime($o->DataCriacao));?></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        <?php endif; ?>

                    </table>

                </div>
                <!-- end widget content -->

            </div>
            <!-- end widget div -->

        </div>
        <!-- end widget -->

    </article>
    <!-- WIDGET END -->

</div>

<!-- end row -->