<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?=$var->name?></title>
    <link rel="stylesheet" href="<?=url('/core/system/assets/css/error.css')?>">
</head>
<body>

<div class="content-error">

    <section>
        <article>
            <header>
                <h1><span>Desculpe! Parece que alguma coisa não está correta :</span></h1>
            </header>
            <ol class="error-info">
                <li><p>Erro <span><?=$var->name?></span></p></li>
                <li><p>Código <span><?=$var->code?></span></p></li>
                <li><p>Mensagem <span><?=$var->message?></span></p></li>
                <li><p>Arquivo <span><?=$var->file?></span></p></li>
                <li><p>Linha <span><?=$var->line?></span></p></li>
            </ol>
        </article>
    </section>


</div>

</body>
</html>